<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'WebSockets\Module'                               => __DIR__ . '/Module.php',
  'WebSockets\Controller\WebsocketCLIController'    => __DIR__ . '/src/Controller/WebsocketCLIController.php',
  'WebSockets\Controller\WebsocketController'       => __DIR__ . '/src/Controller/WebsocketController.php',
  'WebSockets\Exception\ExceptionStrategy'          => __DIR__ . '/src/Exception/ExceptionStrategy.php',
  'WebSockets\Service\WebsocketServer'              => __DIR__ . '/src/Service/WebsocketServer.php',
);
