<?php
// Generated by ZF2's ./bin/classmap_generator.php

return array(
  'WebSockets\Module'                               => __DIR__ .'Module.php',
  'WebSockets\Controller\WebsocketCLIController'    => __DIR__ .'/src/WebSockets/Controller/WebsocketCLIController.php',
  'WebSockets\Controller\WebsocketController'       => __DIR__ .'/src/WebSockets/Controller/WebsocketController.php',
  'WebSockets\Exception\ExceptionStrategy'          => __DIR__ .'/src/WebSockets/Exception/ExceptionStrategy.php',
  'WebSockets\Service\WebsocketServer'              => __DIR__ .'/src/WebSockets/Service/WebsocketServer.php',
  'WebSockets\View\Helper\Socket'		    => __DIR__ .'/src/WebSockets/View/Helper/Socket.php',
);
