<?php
// Generated by ZF2's ./bin/classmap_generator.php
if(!defined('DS')) define('DS', DIRECTORY_SEPARATOR);

return array(
  'WebSockets\Module'                               => __DIR__ .DS.'Module.php',
  'WebSockets\Controller\WebsocketCLIController'    => __DIR__ .DS.'src'.DS.'WebSockets'.DS.'Controller'.DS.'WebsocketCLIController.php',
  'WebSockets\Controller\WebsocketController'       => __DIR__ .DS.'src'.DS.'WebSockets'.DS.'Controller'.DS.'WebsocketController.php',
  'WebSockets\Exception\ExceptionStrategy'          => __DIR__ .DS.'src'.DS.'WebSockets'.DS.'Exception'.DS.'ExceptionStrategy.php',
  'WebSockets\Service\WebsocketServer'              => __DIR__ .DS.'src'.DS.'WebSockets'.DS.'Service'.DS.'WebsocketServer.php',
);
